name: Sync Dotfiles

on:
  push:
    branches: [master]
  schedule:
    - cron: "* */12 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'Rafli Dewanto'
          git config --global user.email 'dewantorafli@gmail.com'

      - name: Check for changes
        run: |
          git add .
          git diff --staged --quiet || (git commit -m "Auto-sync dotfiles" && git push)
